### ISSUE TITLE
bug: Protocol "https:" not supported. Expected "http:"

### ISSUE THREAD

**Issue by AkaraChen** [ionic-team/create-stencil#146]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/stencil/blob/main/.github/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/ionic-team/stencil/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/ionic-team/create-stencil/issues) that already report this problem, without success.

### Create Stencil Version

3.1.1 (latest)

### Current Behavior

```
⠋ Preparing starter
✖ Protocol "https:" not supported. Expected "http:"

⠸ Preparing starter ERROR  Command failed with exit code 1: /Users/akarachen/Library/pnpm/store/v3/tmp/dlx-7575/node_modules/.bin/create-stencil
```

### Expected Behavior

Fetch project success.

### Steps to Reproduce

`pnpm create stencil@latest`

### Additional Information

System: MacOS 13 beta
Pnpm: 7.18.1
Node: 19.2.0

**Comment by AkaraChen** [comment]
This seems to be a problem related to my http proxy... Sorry for the useless report.

**Comment by alicewriteswrongs** [comment]
No worries, happy to help narrow it down, and good luck using Stencil!
