### ISSUE TITLE
Best way to update existing stencil project with starter project.

### ISSUE THREAD

**Issue by dashmug** [ionic-team/create-stencil#17]
I have created a project using the boilerplate that was created by doing `npx create-stencil ionic-pwa myproject`.

Now, when there are new changes with the `ionic-pwa` starter, is there an easy way to update my project with those changes?

**Comment by rwaskiewicz** [comment]
Hey @dashmug 👋 

I apologize that it took this long for someone on the team to get back to you.  While I'm not sure if you're still looking for an answer to your original question, at this time we don't have a way to adopt changes in a previous version of a starter package.  I'm going to label this issue to gauge interest in something like this.

**Comment by rwaskiewicz** [comment]
I'm going to close this issue due to lack of interest from the community. Thanks again!
