### ISSUE TITLE
Typing Pos1/End/Insert/Del/Page Up/Page down result in "undefined"

### ISSUE THREAD

**Issue by RafaelKr** [ionic-team/create-stencil#18]
**How to reproduce:**
- Run `npm init stencil`
- When you are prompted to select a "Project name", type any of these keys:
- Pos1/End/Insert/Del/Page Up/Page down

For me there appears the word `undefined` at the current cursor position in the prompt:
![image](https://user-images.githubusercontent.com/14234815/56967858-5e071400-6b62-11e9-8ae1-e9b3af6a65ea.png)

**Comment by rwaskiewicz** [comment]
Hey @RafaelKr 

I apologize it took so long for a member of the team to get back to you here.  I'm unable to reproduce this issue locally. If you're interested, willing and able, could you attempt to reproduce this in the same shell with the latest version of the CLI? If not, I completely understand.  Once again, I apologize for the lack of communication here.
