### ISSUE TITLE
Building the app breaks npm start

### ISSUE THREAD

**Issue by joeSaad** [ionic-team/create-stencil#26]
This is exactly what I have done, please let me know where I went wrong: 
`npm init stencil`
Using the interactive mode, I used PWA and I have my repo's name set. 

Next I pasted a theme from the [ionic theme generator](https://ionicframework.com/docs/theming/color-generator) into my _app.css_ file, created another sample component. 
Running
`npm start`
Everything looks good as expected. 

Now, I want to build. 
changed in the _stencil.config.ts_ 
by adding both namespace and added the *dist* to my array of outputTargets. 
I followed the instructions for building 
`npm run build`
by adding *main*, *module*, *collection* all instructions coming in from console already. 

After building that one time. 
`npm start` 
fails. _app.css_ cannot be found. 
![image](https://user-images.githubusercontent.com/1170032/63299785-3b794200-c29c-11e9-9782-9a62cac51473.png)

Please advise if this is an issue or intentionally, or what am i missing to make a good usable build where i can use `npm start` even after the build has been done. 

Thanks

**Comment by rwaskiewicz** [comment]
Hey @joeSaad 👋 

I apologize for the amount of time it took for someone to acknowledge this issue, first and foremost.  While it's not the same as having responded to you when you originally submitted this issue, I am trying to actively acknowledge tickets that have been left by the wayside.

As of v2.0.0 of the `create-stencil` cli, we no longer support the Ionic PWA as an output option.  If you're still interested in pursuing this issue, we can recreate this issue in the https://github.com/ionic-team/ionic-pwa-toolkit repository.

Thank you for the time you took to put this ticket together, and I apologize again it went so long unacknowledged.
