### ISSUE TITLE
Rename components starter to component

### ISSUE THREAD

**Issue by juanmiguelbesada** [ionic-team/create-stencil#4]
To me, it feels strange to use:

```bash
npm init stencil components my-component
```
When I just want to make a single web-component, not multiple (plural)

Even, the starter repository is `stencil-component-starter`

WDYT?

**Comment by manucorporat** [comment]
cc @jgw96

**Comment by juanmiguelbesada** [comment]
Fixed in https://github.com/ionic-team/create-stencil/commit/acbc500fd6247c482cdb5e3a735d757b84cb671b
