### ISSUE TITLE
bug: Fresh install, fresh project creation, dev server returns error: Failed to open a WebSocket connection: invalid Connection header: keep-alive.

### ISSUE THREAD

**Issue by jesselee34** [ionic-team/create-stencil#444]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/stencil/blob/main/.github/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/ionic-team/stencil/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/ionic-team/create-stencil/issues) that already report this problem, without success.

### Create Stencil Version

4.9.0

### Current Behavior

After fresh install, and fresh project creation

Server starts on localhost:3333

Chrome tab is opened and shows:

```
Failed to open a WebSocket connection: invalid Connection header: keep-alive.

You cannot access a WebSocket server directly with a browser. You need a WebSocket client.
```

### Expected Behavior

I'd expect the browser to display the default generated web component

### Steps to Reproduce

```
npm install -g create-stencil@latest

npm init stencil

choose component option

cd my-component

npm install

npm start
```

### Additional Information

Windows 11
Node.js 20.1.0
npm 9.6.4

**Comment by rwaskiewicz** [comment]
Hey @jesselee34 👋 

Thanks for the issue report!

I was unable to reproduce this locally following the instructions you provided with the following environment:
- Windows 11
- Node.js 20.1.0
- npm 9.6.4
- create-stencil 3.5.2
- Stencil v4.9.0
- Chrome v120.0.6099.200 (Official Build) (64-bit)

Can you do me a favor and try a few different things for me to help move this forward?
1. If you try the steps to reproduce again, does the issue still occur?
2. In a separate directory, can you try running the steps below and let me know if that works?
    1. `npm init stencil@latest component my-component-2`
    2. `cd my-component-2`
    3. `npm install`
    4. `npm start`
3. Can you let me know which version of Chrome this occurs on? 
4. Are you seeing this in any other browsers like Firefox?

Thanks!

**Comment by jesselee34** [comment]
Yeah, I tried both and I still get the same behavior. Tried in Microsoft edge, same thing.

![Screenshot 2024-02-02 192435](https://github.com/ionic-team/create-stencil/assets/1936617/b0ca7883-2e2e-460d-83e2-cb3bf084d7e7)

A few other things I tried:

1. appending /index.html, and a few other files in www to see if anything would be served. Nope
2. GPT4 suggested I disable any firewalls temporarily, tried that. Nope
3. Googling a bit, seems to have something to do with trying to connect to the server over websocket with the wrong value for the  Connection header. 🤷 

Here's are all the details from the network tab:

![Screenshot 2024-02-02 193606](https://github.com/ionic-team/create-stencil/assets/1936617/99b1b5f6-3579-4f75-8989-b0d000f30326)

**Comment by jesselee34** [comment]
Ok, after looking closer at the response headers I saw that the server is Python/3 which seems strange so I decided to kill the process and try pulling up localhost:3333 and yeah, I have something else running on that port. Not sure what it is, but something's there.

Strange that the dev server didn't throw when attempting to listen on that port.
