### ISSUE TITLE
bug: npm init stencil not working

### ISSUE THREAD

**Issue by stevenbriscoeca** [ionic-team/create-stencil#58]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/stencil/blob/main/.github/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/ionic-team/stencil/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/ionic-team/stencil/issues) that already report this problem, without success.

### Stencil Version

latest

### Current Behavior

When I do npm init stencil I get this : 
node version v16.13.0
npm version 8.1.0

✖ Protocol "https:" not supported. Expected "http:"
![image](https://user-images.githubusercontent.com/3018441/153669173-f6e611f0-bb79-4263-9fff-1de0d2c5c649.png)

I tried with node 17.5.0 and 16.14.0 and I get this error : 
![image](https://user-images.githubusercontent.com/3018441/153668925-64877afc-4380-40d2-bc82-fef7237bdd46.png)

I am using nvm, not sure if that has to do with anything

### Expected Behavior

being able to create a starter app

### Steps to Reproduce

npm init stencil on windows

### Code Reproduction URL

https://github.com/ionic-team/stencil/

### Additional Information

I can't reproduce it in a code reproduction url...it's via cmd

**Comment by rwaskiewicz** [comment]
I tried to replicate this in a Windows 11 VM using the same major versions of NPM and Node (8.3.1, 16.14 respectively) and wasn't able to do so:
![Screen Shot 2022-02-11 at 4 42 32 PM](https://user-images.githubusercontent.com/1930213/153674334-f34c0693-44fd-40fe-add9-01ec82bb45ee.png)

By any chance are you behind a firewall/proxy that could be a factor here?

**Comment by stevenbriscoeca** [comment]
Yeah, it's in a corporate settings with proxies. 

I just cloned this repo instead,
https://github.com/ionic-team/stencil-component-starter

 I think we can close this because the alternative is pretty easy and figuring out the proxies settings might not be worth it in this case.

**Comment by rwaskiewicz** [comment]
👍 Sounds good. Thanks for response!
